name: Continuous integration for Reserbiz Backend

on:
  push:
    branches: [ master, development ]
    paths: [
      .github/workflows, 
      ReserbizAPP.API, 
      ReserbizAPP.Hangfire, 
      ReserbizAPP.LIB, 
      ReserbizAPP.Tests
    ]

  pull_request:
    branches: [ master, developement ]
    paths: [
      .github/workflows, 
      ReserbizAPP.API, 
      ReserbizAPP.Hangfire, 
      ReserbizAPP.LIB, 
      ReserbizAPP.Tests
    ]

jobs:
  build:
    name: Build and Test Reserbiz backend
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Clean Solution
      run: dotnet clean ReSerBiz.sln --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
