name: Continuous integration for Reserbiz Application

on:
  push:
    branches: [master, development]
    paths: [.github/workflows/**, Reserbiz/**]

  pull_request:
    branches: [master, development]
    paths: [.github/workflows/**, Reserbiz/**]

jobs:
  build:
    name: Build and test Reserbiz Application
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: hrueger/setup-nativescript@v1.1.0
        with:
          nativescript-version: '8.2.3'

      - name: Set JAVA_HOME path
        run: echo $env:JAVA_HOME

      - name: Setup Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Install dependencies
        run: npm install
        working-directory: ./Reserbiz

      - name: Build Reserbiz Application
        run: ns build android
        working-directory: ./Reserbiz
