name: Continuous integration for Reserbiz SQL Server

on:
  push:
    branches: [master, development]
    paths:
      [
        .github/workflows/**,
        ReserbizAPP.API/**,
        ReserbizAPP.Hangfire/**,
        ReserbizAPP.LIB/**,
        ReserbizAPP.Tests/**,
        ReserbizAPP.IntegrationTests/**,
      ]

  pull_request:
    branches: [master, development]
    paths:
      [
        .github/workflows/**,
        ReserbizAPP.API/**,
        ReserbizAPP.Hangfire/**,
        ReserbizAPP.LIB/**,
        ReserbizAPP.Tests/**,
        ReserbizAPP.IntegrationTests/**,
      ]

jobs:
  build:
    name: Build and Test Reserbiz SQL Server
    runs-on: windows-latest

    steps:
      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.0.0
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          catalog: nservicebus
          extra-params: 'Max Pool Size=100;'
      - name: Alter schemas
        shell: pwsh
        run: |
          sqlcmd -Q "
            use nservicebus;
            create table tbl_test (id int, name varchar(100));
            insert into tbl_test
            values (1, 'Roi');
            select * from tbl_test;
          "

