name: Continuous integration for Reserbiz SQL Server

on:
  push:
    branches: [master, development]
    paths:
      [
        .github/workflows/**,
        ReserbizAPP.API/**,
        ReserbizAPP.Hangfire/**,
        ReserbizAPP.LIB/**,
        ReserbizAPP.Tests/**,
        ReserbizAPP.IntegrationTests/**,
      ]

  pull_request:
    branches: [master, development]
    paths:
      [
        .github/workflows/**,
        ReserbizAPP.API/**,
        ReserbizAPP.Hangfire/**,
        ReserbizAPP.LIB/**,
        ReserbizAPP.Tests/**,
        ReserbizAPP.IntegrationTests/**,
      ]

jobs:
  build:
    name: Build and Test Reserbiz SQL Server
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Set Environment Variables
        run: |
          echo "ASPNETCORE_ENVIRONMENT=IntegrationTest" >> $env:GITHUB_ENV

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.0.0
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING

      - name: Set up integration test databases
        shell: pwsh
        run: sqlcmd -i script.sql
        working-directory: ./ReserbizAPP.IntegrationTests

      - name: Run Integration Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./ReserbizAPP.IntegrationTests

